### ISSUE TITLE
No automated tests (e.g., `pytest`)

### ISSUE THREAD

**Issue by JDRomano2** [rajarshi008/Scarlet#4]
There are no automated tests. An automated testing framework such as `pytest` or `nose` should be used to test the code. Currently, you simply mention how the user can 'test' the code by running the software using one or more of the benchmark trace files.

**Comment by JDRomano2** [comment]
(review comment for https://github.com/openjournals/joss-reviews/issues/5052)

**Comment by ritamraha** [comment]
> There are no automated tests. An automated testing framework such as `pytest` or `nose` should be used to test the code. Currently, you simply mention how the user can 'test' the code by running the software using one or more of the benchmark trace files.

We have added automated tests in the pytest framework. We have also added instruction in README about how to run them.
