### ISSUE TITLE
No contribution guidelines

### ISSUE THREAD

**Issue by JDRomano2** [rajarshi008/Scarlet#5]
(review comment for https://github.com/openjournals/joss-reviews/issues/5052)

There are no contribution guidelines provided. These can either go in the README under an appropriate heading, or in a separate `CONTRIBUTING.md` file.

**Comment by ritamraha** [comment]
> (review comment for [openjournals/joss-reviews#5052](https://github.com/openjournals/joss-reviews/issues/5052))
> 
> There are no contribution guidelines provided. These can either go in the README under an appropriate heading, or in a separate `CONTRIBUTING.md` file.

We have added the contribution guidelines in a separate section in README.
